baseURL: 
languageCode: en-us
title: Aligner | Translate 10X faster | Online free platform.
theme: hugo-fresh
googleAnalytics: UA-138300699-1
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files


menu:
  # before: []
  after: 
    - name: "Hugo Themes"
      url: "https://themes.gohugo.io/hugo-book/"
      weight: 20

params:
  BookMenuBundle: /menu
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: Translate 10 times faster with Aligner. Free collaboration tool.
  navbarlogo: 
  # Logo (from static/images/logos/___)
    image: logos/logo-new.svg
    link: /
  font:
    name: "Poppins"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Seamleslly create and  organize content in multiple languages.
    # Hero subtitle (optional)
    subtitle: Free multilingual document management tool
    # Button text
    buttontext: Start now â†’
    # Where the main hero button links to
    buttonlink: https://app.aligner.io
    # Button text
    buttontext2: 
    # Where the main hero button links to
    buttonlink2:  
    # Hero image (from static/images/___)
   # image: banner-desktop.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  # Customizable navbar. For a dropdown, add a "sublinks" list.  Features, Pricing, Solutions (dropdown with three elements), Resources
  navbar:
  - title: Features
    url: /features
  - title: Pricing
    url: /pricing
  - title: Blog
    url: /blog/
  - title: Solutions
    sublinks:
    - title: POOL - croudsourced API 
      url: https://pool.aligner.io
    - title: GO - content delivery
      url: https://go.aligner.io
    - title: APP - content management
      url: https://app.aligner.io
 # - title: Resources
  #  url: /resources
  - title: Log in
    url: https://app.aligner.io
  - title: Start free now â†’
    url: https://app.aligner.io
    button: true
  section1:
    enable: false
    title: It's all about simplicity
    subtitle: Instant value in 3 steps
    tiles:
    - title: Upload file
      icon: upload-cloud
      text: Get the value now by going directly into publishing new languages.
      url: /features
      buttonText: See supported formats
    - title: Use Machine Translation
      icon: zap-2
      text: Machine translation provides 95% of accuracy and improves monthly.
      url: /
      buttonText: Try best engines here
    - title: Invite people to proofread
      icon: user-plus
      text: Trackable, easy to fix pieces provide clear call to action to all shareholders
      url: /
      buttonText: Get started
  features:
    enable: true
    title: Features 
    subtitle:  
    buttonlink: /features
    buttonText: See all the features â†’
    list:
    - title: Edit
      text: No hassle with tracking changes across your content in different languages.
      image: /images/textedit.svg
      btnText: 
      btnURL: ""
      btnKlass: "" 
    - title: Translate
      text: Use machine translation to translate the whole document or selectively just a piece.
      image: /images/roboto-logo.svg
      btnText: Call to Action
      btnURL: ""
      btnKlass: ""
    - title: Share
      text: Work with teams and let internal or external collaborators in.
      image: /images/team.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
    - title: Publish
      text: Publish your content to your web, document or other resource.
      image: /images/reload.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
  froalaDesign:
    enable: true
    title: Work on multilingual documents with ease
    subtitle: Made for marketers and content creators.
    features:
    - title: Make changes to all languages
      text: No back and forth emails and files. In Aligner you get syncrhonised all languages automatically when updating pieces of the content.
      image: /images/ai-illustration.svg
      btnText: See it in action â†’
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn" 
    - title: Bring all people together in one place
      text: Assign languages, invite collaborators and always stay on the top of updates.
      image: /images/team-image.svg
      btnText: Start working and invite people â†’
      btnURL: https://app.aligner.io
      btnKlass: "primary-btn"
    - title: Continuously a part of your workflows
      text: Get things syncrhonised with Google Docs and other services without leaving your favourite apps.
      image: /images/flags-illustration.svg
      btnText: Syncronise Google Docs â†’
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn"
    - title: More clarity, faster communication
      text: Aligner help to organise communication between shareholders and deliver the right task. 
      image: /images/version-control.svg
      btnText: Use Aligner now â†’
      btnURL: https://app.aligner.io
      btnKlass: "accent-btn"
  pricing:
    enable: true
    title: Pricing Plans
    subtitle:  
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    btnKlass: "btn-aligner rounded"
    plans:
    - title: Premium
      price: $9 / mo
      icon: /images/plane.svg
      heighlight: Get things done yourself fast
      btnText: Learn more
      btnURL: /pricing
      btnKlass: "btn-aligner rounded"
      features:
        - text: Dual editor
        - text: Google Drive Integrations
        - text: Document Export
        - text: Selective Machine translation
    - title: Freemium
      price: FREE
      icon: /images/hot-air-balloon.svg
      heighlight: Basics that will amaze you
      btnText: Start now
      btnURL: https://app.aligner.io
      btnKlass: "btn-aligner rounded"
      features:
        - text: Dual editor
        - text: Limited Machine Translation
        - text: Unlimited Sharing
        - text: Word and PDF Import
    - title: Team
      price: $29.90 / mo
      icon: /images/sun.svg
      heighlight: Extra team functionality
      btnText: Learn more
      btnURL: "/pricing"
      btnKlass: "btn-aligner rounded"
      features:
        - text: Up to 5 people, next $4
        - text: Versioning 
        - text: Workflows
        - text: Permissions
  CTA:
    enable: true
    title: Get out from the manual routine and shift to Aligner
    subtitle:
    text: Let us help you to explore the possibilities
    btnText: Book a time with us
    btnURL: https://calendly.com/aligner/15min
    btnKlass: "btn-aligner rounded"
    clientlogos: 
  testimonials:
    enable: false
    title: Testimonials
    subtitle: 
    text: With Aligner, you get superspeed at editing content in multiple languages. All synchronisation happens automatically and it's easy to add up new languages to the business.
    name: Co-Founder at Fooddocs
    image: /images/katrin_fooddocs.svg
  pricingInner:
    enable: true
    title: Pricing
    subtitle:
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    btnKlass: "btn-aligner rounded"
    plans:
    - title: Freemium
      price: $0
      icon: /images/plane.svg
      heighlight: Get things done quick
      btnText: Start now â†’
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn"
    - title: Premium
      price: $8.99/mo
      icon: /images/hot-air-balloon.svg
      heighlight: For medium companies
      btnText: Coming soon
      btnURL: "#"
      btnKlass: "primary-btn"
    - title: Team
      price: $29.99/mo
      icon: /images/sun.svg
      heighlight: For large companies
      btnText: Coming soon
      btnURL: "#"
      btnKlass: "secondary-btn"      
    features:
      - list: 
        - Dual editor
        - true
        - true
        - true
      - list: 
        - Languages
        - 3
        - 5
        - 10
      - list: 
        - Documents
        - 40
        - Unlimited
        - Unlimited
      - list: 
        - Syncrhonised styles
        - true
        - true
        - true
      - list: 
        - Machine Translation
        - true
        - true
        - true
      - list: 
        - Selective Machine Translation
        - true
        - true
        - true
      - list: 
        - Import
        - docx and Google docs
        - docx and Google docs, integrations
        - extended functionality
      - list: 
        - Export
        - .docx or Google Docs, PDF
        - .docx or Google Docs, PDF
        - extended functionality
      - list: 
        - Sharing
        - true
        - true
        - true
      - list: 
        - Publishing
        - public links
        - public and private links
        - public and private links
      - list: 
        - Worklows
        - '-'
        - true
        - true
      - list: 
        - Rights
        - '-'
        - true
        - true
        - 
  featuresList:
    enable: false
    title: Features
    subtitle: Work simultaneously with no-matter-how-many languages
    image1: /images/recording.mov
    #image2: /images/hero-image.jpg
    features:
    - title: Auto-Styling
      text: All styles syncrhonised through the languages
      icon: /images/css.svg
    - title: HTML based
      text: Easily use any of the Web components
      icon: /images/html.svg
    - title: Collaboration
      text: Invite colleagues, translators, proofreaders
      icon: /images/collaborate-features.png
    - title: PDF export
      text: Ready to print? We are PDF ready.
      icon: /images/pdf-translate.svg
    - title: Google Docs
      text: Sync with your Google Docs account
      icon: /images/docs.svg
    - title: Microsoft Word
      text: Upload Word content with ease
      icon: /images/word.svg
    - title: Machine Translation
      text: Combination of best engines
      icon: /images/languages.svg
    - title: 136+ Languages
      text: You are covered, globally
      icon: /images/globe.svg
  froalaBlock:
    enable: true
    title: Aligner is built for marketers and creators who care about being productive.
    text: Time. It's all about being effective. Escape back-n-forth emailing, long deadlines. Alinger is made to make things happen instant.
    linktext: "Start exploring all possibilities <i class='fa fa-angle-right'></i>"
    linkurl: https://app.aligner.io
    list:
    - title: Reach new audience
      image: /images/crowd.png
    - title: Do things faster
      image: /images/rocket.svg
    - title: No credit card required
      image: /images/no-credit-card.png
    - title: Cloud
      image: /images/cloud.png
  section2:
    enable: false
    title: Why people use Aligner?
    subtitle: Our users care about being effective.
    features:
    - title: Most efficient formula 
      text: Human input + Machine Translation + Human Proofreading = **10X times faster results**. Just log in and start working.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: users
    - title: Styles automated
      text: Once styles are applied in any of the languages, all others will be syncrhonised. We have reduced necessity of clicks.
      icon: zap
    - title: Choose the people you work with
      text: Feel free to add anyone to your processes with no financial attachments.
      icon: share

  section4:
    enable: false
    title: How does it feel like to be 10X faster?
    subtitle: People love Aligner from different verticals.
    clients:
    - name: Merilin V.
      quote: Getting translations done is 10 times faster in Aligner. Being faster means youâ€™re going to bring services into new markets quicker. We want to use the best tools that help us to be more efficient
      job: Office Manager
      img: 1
    - name: Anari H.
      quote: I can translate articles in Aligner and improve my content on the go, just like I need it. With machine learning I expect Aligner to become the best tool in the industry.
      job: Journalist
      img: 2
    - name: Philip S.
      quote: Aligner is the fast track to roll out real estate listings and materials in different languages. Itâ€™s easy to use and compared to Google Translate we can edit, store and share translated listings right away.
      job: Real Estate Broker
      img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: logo-new.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://www.facebook.com/align.and.scale/
      icon: facebook
    - link: https://www.instagram.com/align_and_scale/
      icon: instagram
    - link: https://www.linkedin.com/company/aligner
      icon: linkedin
    bulmalogo: false
    quicklinks:
      column1:
        title: "Legal"
        links:
        - text: Privacy Policy
          link: /privacy-policy
        - text: Delivery Policy
          link: /delivery-policy
        - text: Terms of use
          link: /terms-of-use
      column2:
        title: "Product"
        links:
        - text: Plans
          link: /pricing
        - text: Blog
          link: /blog
        - text: Features
          link: /features
      column3:
        title: "Resources"
        links:
        - text: Aligner POOL
          link: https://pool.aligner.io
        - text: Aligner GO
          link: https://go.aligner.io
        - text: Eesti Keeles ðŸ‡ªðŸ‡ª
          link: /ee
       # - text: Getting Started
       #   link: 


          
