baseURL: 
languageCode: en-us
title: Aligner- Multilingual content management
theme: hugo-fresh
googleAnalytics: UA-138300699-1
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files


menu:
  # before: []
  after: 
    - name: "Hugo Themes"
      url: "https://themes.gohugo.io/hugo-book/"
      weight: 20

params:
  BookMenuBundle: /menu
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo: 
  # Logo (from static/images/logos/___)
    image: logos/logo-new.svg
    link: /
  font:
    name: "Nunito"
    sizes: [400,600]
  hero:
    # Main hero title
    title: World's 1st multilingual<br> content management platform.
    # Hero subtitle (optional)
    subtitle: Providing an intuitive workflow for your ever growing localisation problems.
    # Button text
    buttontext: Start free now →
    # Where the main hero button links to
    buttonlink: https://app.aligner.io
    # Button text
    buttontext2: 
    # Where the main hero button links to
    buttonlink2:  
    # Hero image (from static/images/___)
  #  image: banner-desktop.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.  Features, Pricing, Solutions (dropdown with three elements), Resources
  navbar:
  - title: Features
    url: /#features
  - title: Pricing
    url: /pricing
  - title: Blog
    url: /blog/
  - title: Solutions
    sublinks:
    - title: POOL - croudsourced API 
      url: https://pool.aligner.io
    - title: GO - content delivery
      url: https://go.aligner.io
    - title: APP - content management
      url: https://app.aligner.io
 # - title: Resources
    url: /resources
  - title: Log in
    url: https://app.aligner.io
  - title: Start free now →
    url: https://app.aligner.io
    button: true
  section1:
    enable: false
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  features:
    enable: true
    title: Features 
    subtitle:  
    buttonlink: https://app.aligner.io
    buttonText: Get started here →
    list:
    - title: Matrix editor
      text: No hassle with tracking changes across your content in different languages.
      image: /images/textedit.svg
      btnText: 
      btnURL: ""
      btnKlass: "" 
    - title: Machine translation
      text: Use machine translation to translate the whole document or selectively just a piece.
      image: /images/roboto-logo.svg
      btnText: Call to Action
      btnURL: ""
      btnKlass: ""
    - title: Assign languages
      text: Work with teams and let internal or external collaborators in.
      image: /images/team.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
    - title: Export to destination
      text: Publish your content to your web, document or other resource.
      image: /images/reload.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
  froalaDesign:
    enable: true
    title: Aligner
    subtitle: Made for marketers and content creators to work on multilingual content with ease.
    features:
    - title: Seamless multilingual content syncronization via changes matrix
      text: No back and forth emails and files. Get syncrhonised all languages automatically when updating pieces of the content.
      image: /images/ai-illustration.svg
      btnText: See it in action →
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn" 
    - title: Create your content with your team
      text: Assign languages, invite collaborators and never stay alert on missing work done.
      image: /images/team-image.svg
      btnText: Start working and invite people →
      btnURL: https://app.aligner.io
      btnKlass: "primary-btn"
    - title: Keep your multilingual paperwork in one place
      text: Get things syncrhonised with Google Docs and other services without leaving your favourite apps.
      image: /images/flags-illustration.svg
      btnText: Syncronise Google Docs →
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn"
    - title: Keep track of changes and never miss any change
      text: Aligner keeps track of changes done in multiple languages and provides selective machine translation to fix it rightaway
      image: /images/version-control.svg
      btnText: See how it works →
      btnURL: https://app.aligner.io
      btnKlass: "accent-btn"
  pricing:
    enable: true
    title: Pricing Plans
    subtitle:  
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    btnKlass: "btn-aligner rounded"
    plans:
    - title: Premium
      price: $9 / mo
      icon: /images/plane.svg
      heighlight: Get things done yourself fast
      btnText: Learn more
      btnURL: /pricing
      btnKlass: "btn-aligner rounded"
      features:
        - text: Matrix editor
        - text: Integrations
        - text: Private sharing
        - text: Machine translation
    - title: Freemium
      price: FREE
      icon: /images/hot-air-balloon.svg
      heighlight: Basics that will amaze you
      btnText: Start now
      btnURL: https://app.aligner.io
      btnKlass: "btn-aligner rounded"
      features:
        - text: Matrix editor and MT translation
        - text: sharing
        - text: true
        - text: export
    - title: Team
      price: $29.90 / mo
      icon: /images/sun.svg
      heighlight: Extra team functionality
      btnText: Learn more
      btnURL: "/pricing"
      btnKlass: "btn-aligner rounded"
      features:
        - text: Up to 5 people, next $4
        - text: Versioning 
        - text: Workflows
        - text: Permissions
  CTA:
    enable: true
    title: Get out from the manual routine and shift to Aligner
    subtitle: 
    text: Let us help you to explore the possibilities
    btnText: Book a time with us
    btnURL: https://calendly.com/aligner/15min
    btnKlass: "btn-aligner rounded"
    clientlogos: 
  testimonials:
    enable: false
    title: Testimonials
    subtitle: 
    text: With Aligner, you get superspeed at editing content in multiple languages. All synchronisation happens automatically and it's easy to add up new languages to the business.
    name: Co-Founder at Fooddocs
    image: /images/katrin_fooddocs.svg
  pricingInner:
    enable: true
    title: Pricing built for individuals and teams
    subtitle:  
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    btnKlass: "btn-aligner rounded"
    plans:
    - title: Freemium
      price: $0
      icon: /images/plane.svg
      heighlight: Get things done quick
      btnText: Start now →
      btnURL: https://app.aligner.io
      btnKlass: "secondary-btn"
    - title: Premium
      price: $8.99
      icon: /images/hot-air-balloon.svg
      heighlight: For medium companies
      btnText: Coming soon
      btnURL: "#"
      btnKlass: "primary-btn"
    - title: Team
      price: $29.99
      icon: /images/sun.svg
      heighlight: For large companies
      btnText: Coming soon
      btnURL: "#"
      btnKlass: "secondary-btn"      
    features:
      - list: 
        - Matrix editor
        - true
        - true
        - true
      - list: 
        - Languages
        - 3
        - 5
        - 10
      - list: 
        - Documents
        - 20
        - Unlimited
        - Unlimited
      - list:
        - Storage
        - 500mb
        - 2GB
        - 5GB
      - list: 
        - Syncrhonised styles
        - true
        - true
        - true
      - list: 
        - Machine Translation
        - true
        - true
        - true
      - list:
        - Choose MT engines
        - "-"
        - true
        - true
      - list: 
        - Import
        - docx and Google docs
        - docx and Google docs, integrations
        - extended functionality
      - list: 
        - Export
        - .docx or Google Docs, PDF
        - .docx or Google Docs, PDF
        - extended functionality
      - list: 
        - Sharing
        - true
        - true
        - true
      - list: 
        - Publishing
        - public links
        - public and private links
        - public and private links
      - list: 
        - Worklows
        - '-'
        - true
        - true
      - list: 
        - Rights
        - '-'
        - true
        - true
        - 
  featuresList:
    enable: false
    title: Features
    subtitle: 
    features:
    - title: Feature One
      text: Even the all-powerful Pointing has no control about the blind texts      
      icon: /images/feature-sm1.jpg
    - title: Feature Two
      text: Separated they live in Bookmarksgrove right at the coast    
      icon: /images/feature-sm2.jpg
    - title: Feature Three
      text: A small river named Duden flows by their place and supplies it  
      icon: /images/feature-sm3.jpg
    - title: Feature Four
      text: Far far away, behind the word mountains, far from the countries 
      icon: /images/feature-sm4.jpg
    - title: Feature Five
      text: On her way she met a copy. The copy warned the Little Blind Text.
      icon: /images/feature-sm5.jpg
    - title: Feature Six
      text: Far far away, behind the word mountains, far from the countries
      icon: /images/feature-sm6.jpg
    - title: Feature Seven
      text: Duden flows by their place far far away, behind the word mountains.
      icon: /images/feature-sm7.jpg
    - title: Feature Eight
      text: Separated they live in Bookmarksgrove right at the coast
      icon: /images/feature-sm8.jpg
  froalaBlock:
    enable: true
    title: Froala Design Blocks is simply ahead the word mountains
    text: Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
    linktext: "Explore all features <i class='fa fa-angle-right'></i>"
    linkurl: "#"
    list:
    - title: Feature One
      image: /images/git.jpg
    - title: Feature Two
      image: /images/feature-sm5.jpg
    - title: Feature Three
      image: /images/feature-sm1.jpg
    - title: Feature Four
      image: /images/feature-sm7.jpg
  section2:
    enable: false
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed

  section4:
    enable: false
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: logo-new.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
    - link: https://www.facebook.com/align.and.scale/
      icon: facebook
    bulmalogo: false
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Privacy Policy
          link: /privacy-policy
        - text: Delivery Policy
          link: /delivery-policy
        - text: Terms of use
          link: /terms-of-use
      column2:
        title: "Pricing"
        links:
        - text: Plans
          link: /pricing
        - text: Blog
          link: /blog
        #- text: Contact
       #   link: /contacts
     # column3:
      #  title: "Resources"
       # links:
       # - text: Latest news
       #   link: /blog/first
       # - text: Tech articles
       #   link: /blog/second


          