baseURL: 
languageCode: en-us
title: Hugo Fresh Theme
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files
      

menu:
  # before: []
  after:
    - name: "Github"
      url: "https://github.com/alex-shpak/hugo-book"
      weight: 10
    - name: "Hugo Themes"
      url: "https://themes.gohugo.io/hugo-book/"
      weight: 20

params:
  BookMenuBundle: /menu
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Libre Franklin"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Aligner - multilingual content management platform. 
    # Hero subtitle (optional)
    subtitle: Providing an intuitive workflow for you ever growing localisation problems.
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#" 
    # Button text
    buttontext2: Book a demo
    # Where the main hero button links to
    buttonlink2: "#" 
    # Hero image (from static/images/___)
    image: girlseditor.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.  Features, Pricing, Solutions (dropdown with three elements), Resources
  navbar:
  - title: Features
    url: /#features
  - title: Pricing
    url: /#pricing
  - title: Solutions
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: Resources
    url: /resources
  - title: Login
    url: /login    
  - title: Sign up
    url: /
    button: true
  section1:
    enable: false
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  features:
    enable: true
    title: Features 
    subtitle:  
    buttonlink: "/features"
    buttonText: Learn More About Features
    list:
    - title: Feature One
      text: Far far away, behind the word mountains, far from the countries
      image: /images/textedit.svg
      btnText: 
      btnURL: ""
      btnKlass: "" 
    - title: Feature Two
      text: Separated they live in Bookmarksgrove right at the coast
      image: /images/roboto-logo.svg
      btnText: Call to Action
      btnURL: ""
      btnKlass: ""
    - title: Feature Three
      text: A small river named Duden flows by their place and supplies it
      image: /images/team.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
    - title: Feature Four
      text: Duden flows by their place far far away, behind the word mountains.
      image: /images/reload.svg
      btnText: 
      btnURL: ""
      btnKlass: ""
  froalaDesign:
    enable: true
    title: Froala Design Blocks
    subtitle: Over 170 responsive design blocks ready to be used in your web or mobile apps. 
    features:
    - title: Seamless multilingual content syncronization via changes matrix
      text: A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.
      image: /images/ai-illustration.svg
      btnText: Call to Action
      btnURL: "#"
      btnKlass: "secondary-btn" 
    - title: Handle your content with your team or fall back onto professional hired help through Aligner
      text: Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.
      image: /images/team-image.svg
      btnText: Call to Action
      btnURL: "#"
      btnKlass: "primary-btn"
    - title: Multiple content translation options for a variety of budgets
      text: Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
      image: /images/flags-illustration.svg
      btnText: Call to Action
      btnURL: "#"
      btnKlass: "secondary-btn"
    - title: A constantly expanding platform for a multitude of different types of content across all fields
      text: Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
      image: /images/version-control.svg
      btnText: Download
      btnURL: "#"
      btnKlass: "accent-btn"
  pricing:
    enable: true
    title: Pricing Plans
    subtitle:  
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    plans:
    - title: Startup
      price: 9.90
      icon: /images/plane.svg
      heighlight: For small companies
      btnText: Choose Plan
      btnURL: "#"
      btnKlass: "secondary-btn"
      features:
        - text: 10 hours of support
        - text: 40MB of storage
        - text: Subdomain
    - title: Standard
      price: 19.90
      icon: /images/hot-air-balloon.svg
      heighlight: For medium companies
      btnText: Choose Plan
      btnURL: "#"
      btnKlass: "primary-btn"
      features:
        - text: 10 hours of support
        - text: 40MB of storage
        - text: Subdomain
    - title: Business
      price: 29.90
      icon: /images/sun.svg
      heighlight: For large companies
      btnText: Choose Plan
      btnURL: "#"
      btnKlass: "secondary-btn"
      features:
        - text: 10 hours of support
        - text: 40MB of storage
        - text: Subdomain
  CTA:
    enable: true
    title: Call to Action
    subtitle: Fortune 100 companies are using our products
    text: Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts
    btnText: Download
    btnURL: "#"
    btnKlass: "accent-btn"
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  testimonials:
    enable: true
    title: Testimonials
    subtitle: 
    text: Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
    name: Co-founder at Company
    image: /images/illustrations/faces/2.png
  pricingInner:
    enable: true
    title: Pricing Plans
    subtitle:  
    buttonlink: "/pricing"
    buttonText: learn more about pricing
    plans:
    - title: Hobby
      price: $99
      icon: /images/plane.svg
      heighlight: For small companies
      btnText: Buy Now
      btnURL: "#"
      btnKlass: "secondary-btn"
    - title: Professional
      price: $399
      icon: /images/hot-air-balloon.svg
      heighlight: For medium companies
      btnText: Buy Now
      btnURL: "#"
      btnKlass: "primary-btn"
    - title: Business
      price: $899
      icon: /images/sun.svg
      heighlight: For large companies
      btnText: Buy Now
      btnURL: "#"
      btnKlass: "secondary-btn"
    - title: Enterprise
      price: Call us
      icon: /images/sun.svg
      heighlight: For large companies
      btnText: Buy Now
      btnURL: "#"
      btnKlass: "secondary-btn"      
    features:
      - list: 
        - Support
        - 3 months
        - 6 months
        - 12 months
        - Custom
      - list: 
        - Full source code
        - true
        - true
        - true
        - true
      - list: 
        - SaaS / Subscription
        - true
        - true
        - true
        - true
      - list: 
        - Intranet
        - 
        - true
        - true
        - true
      - list: 
        - Downloadable Software
        - 
        - 
        - true
        - true
      - list: 
        - Redistribute
        - 
        - 
        - 
        - true
      - list: 
        - Custom code
        - 
        - 
        - 
        - true
  section2:
    enable: false
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    enable: false
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    enable: false
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second


          